# Section 7: Controlling Workflow & Job Execution

# Evaluate conditions via expressions

# Jobs
# - `if` field

# Steps
# - `if` field
# - `continue-on-error` field

# Special Conditional Functions
# - failure()   - true when any previous Step or Job failed
# - success()   - true when none of the previous steps have failed
# - always()    - causes the step to always execute even when cancelled
# - cancelled() - true if the workflow has been cancelled

name: Reusable
on:
  # run workflow when called by another workflow
  # will not trigger actual execution of "Reusable" workflow but instead included in "Use Reusable" workflow
  workflow_call:
    # define "inputs" or parameters for this workflow
    inputs:
      artifact-name:
        description: "The name of the deployable artifact files"
        # required: true
        required: false
        default: dist # default value when not required or not provided
        type: string
    # secrets:
    #   some-secret:
    #     required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          # https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Deploy
        run: echo "Deploying..."
